service: lambda-service

plugins:
  - serverless-offline

provider:
  name: aws
  runtime: nodejs20.x
  environment:
    NODE_ENV: local
    NODE_OPTIONS: '--enable-source-maps'

functions:
  createProduct:
    handler: dist/index.productCreateHandler
    events:
      - http:
          path: products
          method: POST
  listProduct:
    handler: dist/index.productListHandler
    events:
      - http:
          path: products
          method: GET

custom:
  serverless-offline:
    port: 4000
    noTimeout: true
    reloadHandler: true
    noPrependStageInUrl: true
